name: release
on:
  workflow_dispatch:
    inputs:
      wkhtmltopdf_ref:
        description: 'Branch/Tag to use from the HUMENTH/wkhtmltopdf repository'
        required: true
      packaging_release:
        description: 'Release to create in HUMENTH/packaging repository'
        required: true
      packaging_iteration:
        description: 'Iteration (useful for tagged releases)'
        default: '1'
        required: true

jobs:
  docker:
    runs-on: ubuntu-22.04  # Updated to a more recent version of Ubuntu
    strategy:
      matrix:
        package_target:
          - almalinux8-aarch64
          - almalinux8-ppc64le
          - almalinux8-x86_64
          - almalinux9-aarch64
          - almalinux9-ppc64le
          - almalinux9-x86_64
          - bionic-ppc64el
          - bookworm-amd64
          - bookworm-arm64
          - bookworm-i386
          - bookworm-ppc64el
          - buster-ppc64el
          - bullseye-amd64
          - bullseye-arm64
          - bullseye-i386
          - bullseye-ppc64el
          - fedora37-aarch64
          - fedora37-x86_64
          - focal-ppc64el
          - jammy-amd64
          - jammy-arm64
          - jammy-ppc64el
          - noble-amd64
          - noble-arm64
          - noble-ppc64el
          - raspberrypi.bookworm-armhf
          - raspberrypi.bullseye-armhf
      fail-fast: false
    steps:
      - name: configure docker
        run:  |
          echo '{ "experimental": true }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      
      - name: checkout packaging
        uses: actions/checkout@v3  # Updated to use v3
        with:
          path: packaging

      - name: checkout wkhtmltopdf with submodules
        uses: actions/checkout@v3  # Updated to use v3
        with:
          repository: HUMENTH/wkhtmltopdf
          path: wkhtmltopdf
          submodules: true
          ref: ${{ github.event.inputs.wkhtmltopdf_ref }}

      - name: build
        run: cd packaging && python3 ./build package-docker --iteration ${{ github.event.inputs.packaging_iteration }} ${{ matrix.package_target }} ../wkhtmltopdf
        # Removed the --clean flag to avoid unnecessary long build times; add it if absolutely necessary

      - name: Test the build (Optional but recommended)
        run: |
          echo "Running tests for the built packages..."
          # Add your test commands here to verify the packages are correctly built

      - name: Archive build logs in case of failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: packaging/logs  # Adjust the path to where your build logs are located

      - name: release
        uses: softprops/action-gh-release@v0.1.14
        with:
          name: ${{ github.event.inputs.packaging_release }}
          tag_name: ${{ github.event.inputs.packaging_release }}-${{ github.event.inputs.packaging_iteration }}
          target_commitish: ${{ github.sha }}
          files: "packaging/targets/wkhtmltox*.*"
          fail_on_unmatched_files: false
          draft: true
          body: All packages were built and uploaded automatically as a part of [this run](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}), using this [wkhtmltopdf branch/tag](https://github.com/wkhtmltopdf/wkhtmltopdf/tree/${{ github.event.inputs.wkhtmltopdf_ref }}).
